# Generated by Django 2.0.6 on 2018-06-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gather_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest-connection+', to='gather_api.Node')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source-connection+', to='gather_api.Node')),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
