# Generated by Django 2.0.6 on 2018-06-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather_api', '0002_auto_20180619_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
