# Generated by Django 2.0.6 on 2018-06-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather_api', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
